# Generated by Django 3.0 on 2020-07-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200626_1835'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
