# Generated by Django 3.0 on 2020-07-23 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_auto_20200722_1436'),
        
    ]

    operations = [
    ]
