# Generated by Django 3.0 on 2020-08-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20200821_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='caption',
            new_name='informal_caption',
        ),
        migrations.AddField(
            model_name='image',
            name='formal_caption',
            field=models.CharField(default='caption', max_length=500),
        ),
    ]
