# Generated by Django 3.0 on 2020-06-08 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_auto_20200608_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentteam',
            name='name',
        ),
        migrations.RemoveField(
            model_name='pastteam',
            name='address',
        ),
        migrations.AddField(
            model_name='currentteam',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to='current_team/'),
        ),
        migrations.AddField(
            model_name='currentteam',
            name='year',
            field=models.IntegerField(default='2020', null=True),
        ),
        migrations.AddField(
            model_name='pastteam',
            name='years',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='current_team/faculty/'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notablealumni',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='notablealumni',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='past_team/notable_alumni'),
        ),
        migrations.AlterField(
            model_name='notablealumni',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='notablealumni',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notable_alumni_images', to='team.PastTeam'),
        ),
        migrations.AlterField(
            model_name='oc',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='oc',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='current_team/OC/'),
        ),
        migrations.AlterField(
            model_name='oc',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pastoc',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pastoc',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='past_team/past_oc'),
        ),
        migrations.AlterField(
            model_name='pastoc',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='pastoc',
            name='property',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='past_oc_images', to='team.PastTeam'),
        ),
        migrations.AlterField(
            model_name='studentadvisors',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentadvisors',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='current_team/student_advisors/'),
        ),
        migrations.AlterField(
            model_name='studentadvisors',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='current_team/team_members/'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
