# Generated by Django 3.0 on 2020-06-08 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_auto_20200608_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team/current_team/faculty/'),
        ),
        migrations.AlterField(
            model_name='notablealumni',
            name='image',
            field=models.ImageField(blank=True, default='team/default.png', null=True, upload_to='team/past_team/notable_alumni'),
        ),
        migrations.AlterField(
            model_name='oc',
            name='image',
            field=models.ImageField(blank=True, default='team/default.png', null=True, upload_to='team/current_team/OC/'),
        ),
        migrations.AlterField(
            model_name='pastoc',
            name='image',
            field=models.ImageField(blank=True, default='team/default.png', null=True, upload_to='team/past_team/past_oc'),
        ),
        migrations.AlterField(
            model_name='pastteam',
            name='years',
            field=models.CharField(default='2015-2019', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='studentadvisors',
            name='image',
            field=models.ImageField(blank=True, default='team/default.png', null=True, upload_to='team/current_team/student_advisors/'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='image',
            field=models.ImageField(blank=True, default='team/default.png', null=True, upload_to='team/current_team/team_members/'),
        ),
    ]
