# Generated by Django 3.0 on 2020-06-09 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0010_auto_20200609_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oc',
            name='yr_dept',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
