# Generated by Django 3.0.7 on 2020-06-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_auto_20200609_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentteam',
            name='group_photo',
            field=models.ImageField(blank=True, null=True, upload_to='team/'),
        ),
    ]
