# Generated by Django 3.0 on 2020-07-07 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0014_auto_20200707_2232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oc',
            old_name='project',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='studentadvisor',
            old_name='project',
            new_name='team',
        ),
        migrations.RenameField(
            model_name='teammember',
            old_name='project',
            new_name='team',
        ),
    ]
