# Generated by Django 3.0 on 2020-07-20 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_auto_20200707_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
