# Generated by Django 3.0 on 2020-07-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_auto_20200720_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='division',
            field=models.CharField(blank=True, default='UMIC', max_length=50, null=True),
        ),
    ]
