# Generated by Django 3.0 on 2020-08-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_faculty_division'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentadvisor',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
