# Generated by Django 3.0 on 2020-06-05 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sponsor',
            name='sponsor_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/img/'),
        ),
    ]
